export const DEFAULT_CATS = [
  { id: 'avocados', name: 'Aguacates', emoji: '🥑', color: '#16a34a' },
  { id: 'bananas', name: 'Bananas/Plátanos', emoji: '🍌', color: '#ca8a04' },
  { id: 'mangos', name: 'Mangos', emoji: '🥭', color: '#ea580c' },
  { id: 'fruits', name: 'Frutas', emoji: '🍓', color: '#db2777' },
  { id: 'papaya', name: 'Papaya/Melón', emoji: '🍈', color: '#f97316' },
  { id: 'citrus', name: 'Cítricos', emoji: '🍋', color: '#eab308' },
  { id: 'peppers', name: 'Pimientos/Chiles', emoji: '🌶', color: '#dc2626' },
  { id: 'vegetables', name: 'Vegetales', emoji: '🥬', color: '#059669' },
  { id: 'onion', name: 'Cebollas', emoji: '🧅', color: '#7c3aed' },
  { id: 'yam', name: 'Ñame/Papa Dulce', emoji: '🍠', color: '#92400e' },
  { id: 'apples', name: 'Manzanas', emoji: '🍎', color: '#b91c1c' },
  { id: 'roots', name: 'Raíces/Tubérculos', emoji: '🌿', color: '#78350f' },
  { id: 'squash', name: 'Calabazas/Chayotes', emoji: '🫑', color: '#4d7c0f' },
  { id: 'herbs', name: 'Hierbas', emoji: '🌱', color: '#065f46' },
  { id: 'garlic', name: 'Ajo/Jengibre', emoji: '🧄', color: '#a16207' },
  { id: 'tomatoes', name: 'Tomates', emoji: '🍅', color: '#b91c1c' },
  { id: 'others', name: 'Otros', emoji: '📦', color: '#475569' },
]

export const DEFAULT_PRODUCTS = [
  { id: 1, category_id: 'avocados', name: "Avocado Villita 48'" },
  { id: 2, category_id: 'avocados', name: "Avocado Mex 40'" },
  { id: 3, category_id: 'avocados', name: "Avocado Villita 36'" },
  { id: 4, category_id: 'avocados', name: "Avocado 22' DR air" },
  { id: 5, category_id: 'bananas', name: 'Banana yellow turning' },
  { id: 6, category_id: 'bananas', name: 'Banana Green DARIAN' },
  { id: 7, category_id: 'bananas', name: 'Banana Green NICO' },
  { id: 8, category_id: 'bananas', name: 'Banana Leaf' },
  { id: 9, category_id: 'bananas', name: 'Banana Manzano' },
  { id: 10, category_id: 'bananas', name: 'Banana Flower 40' },
  { id: 11, category_id: 'bananas', name: 'Banana thai 33lb' },
  { id: 12, category_id: 'bananas', name: 'Yellow Plantain Turbana' },
  { id: 13, category_id: 'mangos', name: 'Mango Tommy #1' },
  { id: 14, category_id: 'mangos', name: 'Mango Haden #1' },
  { id: 15, category_id: 'mangos', name: 'Mango CRIOLLO 20lb' },
  { id: 16, category_id: 'mangos', name: 'Green mango 50lb PR' },
  { id: 17, category_id: 'mangos', name: 'Baby Green mango' },
  { id: 18, category_id: 'mangos', name: "Mango cabello 14' mex" },
  { id: 19, category_id: 'mangos', name: "Mango cabello 12'" },
  { id: 20, category_id: 'mangos', name: 'Mango Mingolo 9ct 10CT' },
  { id: 21, category_id: 'mangos', name: 'Mango oro' },
  { id: 22, category_id: 'fruits', name: 'CHIRIMOYA 10LB' },
  { id: 23, category_id: 'fruits', name: 'Green sugar cane' },
  { id: 24, category_id: 'fruits', name: 'Red Sugar Cane 10CTT' },
  { id: 25, category_id: 'fruits', name: 'Coconut WHITE' },
  { id: 26, category_id: 'fruits', name: 'Coconut mexican bag' },
  { id: 27, category_id: 'fruits', name: 'Coconut YOUNG 9ct' },
  { id: 28, category_id: 'fruits', name: 'Coconut dry TURBANA' },
  { id: 29, category_id: 'fruits', name: 'Cactus green tuna' },
  { id: 30, category_id: 'fruits', name: 'CACTUS RED TUNA' },
  { id: 31, category_id: 'fruits', name: 'Cherry 10x1lb' },
  { id: 32, category_id: 'fruits', name: 'Dragon Fruit White 6ct' },
  { id: 33, category_id: 'fruits', name: 'Dragon Fruit Yellow 6ct AIR' },
  { id: 34, category_id: 'fruits', name: 'Dragon Fruit Red 6ct' },
  { id: 35, category_id: 'fruits', name: 'Guava mexican 13lb' },
  { id: 36, category_id: 'fruits', name: 'Guava Thai FL' },
  { id: 37, category_id: 'fruits', name: 'Guanabana 10lb' },
  { id: 38, category_id: 'fruits', name: 'Jicama 20lb mex small' },
  { id: 39, category_id: 'fruits', name: 'JOCOTE 20 LB Florida' },
  { id: 40, category_id: 'fruits', name: 'Zapote mamey 50LB' },
  { id: 41, category_id: 'fruits', name: 'Zapote mamey 25lb' },
  { id: 42, category_id: 'fruits', name: 'Nispero 25LB' },
  { id: 43, category_id: 'fruits', name: 'Nance Garabato 30 LBS' },
  { id: 44, category_id: 'fruits', name: 'Pomegranate Israel 6CT' },
  { id: 45, category_id: 'fruits', name: 'Pineapple 6CT' },
  { id: 46, category_id: 'fruits', name: 'PEANUT FRESH 35LB' },
  { id: 47, category_id: 'fruits', name: 'Sand Pear' },
  { id: 48, category_id: 'fruits', name: 'Ramutan mex 15lb' },
  { id: 49, category_id: 'fruits', name: 'Watermelon seeded 28ct' },
  { id: 50, category_id: 'fruits', name: 'Watermelon seedless 36ct' },
  { id: 51, category_id: 'fruits', name: 'Watermelon yellow Seedless 36ct' },
  { id: 52, category_id: 'papaya', name: 'Green papaya panama' },
  { id: 53, category_id: 'papaya', name: "Papaya CHULA 8x9" },
  { id: 54, category_id: 'papaya', name: "Papaya MAMA CHEDES 8'9'" },
  { id: 55, category_id: 'papaya', name: "PAPAYA NECTAR 8'9" },
  { id: 56, category_id: 'citrus', name: 'Lime 200ct mex' },
  { id: 57, category_id: 'citrus', name: 'Lime 200ct colombia' },
  { id: 58, category_id: 'citrus', name: 'Lime 175ct colombia' },
  { id: 59, category_id: 'citrus', name: 'Sour Orange' },
  { id: 60, category_id: 'citrus', name: 'Mandarine 10kg 2x murcotte' },
  { id: 61, category_id: 'citrus', name: 'Mandarine 10kg 3x murcotte' },
  { id: 62, category_id: 'citrus', name: 'Mandarine 10kg 4x murcotte' },
  { id: 63, category_id: 'citrus', name: 'Mandarine 10kg orri 2x' },
  { id: 64, category_id: 'citrus', name: 'Mandarine Bag 10kg 31lb' },
  { id: 65, category_id: 'peppers', name: 'Green thai chili' },
  { id: 66, category_id: 'peppers', name: 'Red thai chili' },
  { id: 67, category_id: 'peppers', name: 'Habanero Red 8lbs' },
  { id: 68, category_id: 'peppers', name: 'Habanero Orange 8lb' },
  { id: 69, category_id: 'peppers', name: 'Habanero mix' },
  { id: 70, category_id: 'peppers', name: 'Habanero Green 8lb' },
  { id: 71, category_id: 'peppers', name: 'Chile Chiltepe bandejas' },
  { id: 72, category_id: 'peppers', name: 'Pepper Jalapeno 35lb' },
  { id: 73, category_id: 'vegetables', name: 'Aloe Vera' },
  { id: 74, category_id: 'vegetables', name: 'Beans fresh vaina 28lb' },
  { id: 75, category_id: 'vegetables', name: 'BeansDesgr Rojo 25lb' },
  { id: 76, category_id: 'vegetables', name: 'BeansDesgr Negro 25lb' },
  { id: 77, category_id: 'vegetables', name: 'Beet loose 25' },
  { id: 78, category_id: 'vegetables', name: 'Beet 12 bunch' },
  { id: 79, category_id: 'vegetables', name: 'BONIATO FL 40LB' },
  { id: 80, category_id: 'vegetables', name: 'Cabbage BOX' },
  { id: 81, category_id: 'vegetables', name: 'Nopal Cactus Leaf 35lb' },
  { id: 82, category_id: 'vegetables', name: 'Carrot Loose JUMBO 50lb' },
  { id: 83, category_id: 'vegetables', name: 'Corn Yellow 48ct' },
  { id: 84, category_id: 'vegetables', name: 'Corn Bicolor 48ct' },
  { id: 85, category_id: 'vegetables', name: 'Cucumber Large mex' },
  { id: 86, category_id: 'vegetables', name: 'CHINESE EGG PLANT HON' },
  { id: 87, category_id: 'vegetables', name: 'INDIAN EGG PLANT' },
  { id: 88, category_id: 'vegetables', name: 'Chive mex 25lb' },
  { id: 89, category_id: 'vegetables', name: 'Green beans wood' },
  { id: 90, category_id: 'vegetables', name: 'Lettuce Cello 24ct cali' },
  { id: 91, category_id: 'vegetables', name: 'LOROCO 12 LB' },
  { id: 92, category_id: 'vegetables', name: 'OKRA HOND 15lb' },
  { id: 93, category_id: 'vegetables', name: 'PACAYA 15 LB' },
  { id: 94, category_id: 'vegetables', name: 'SHALLOT 5x8' },
  { id: 95, category_id: 'onion', name: 'Onion Yellow 50lbs' },
  { id: 96, category_id: 'onion', name: 'Onion white 50lb' },
  { id: 97, category_id: 'onion', name: 'Onion Red 25lb' },
  { id: 98, category_id: 'onion', name: 'Onion cambray 40ct' },
  { id: 99, category_id: 'onion', name: 'Onion green Canada 48CT' },
  { id: 100, category_id: 'yam', name: 'Ghana Yam NEW' },
  { id: 101, category_id: 'yam', name: 'White Yam 30lb' },
  { id: 102, category_id: 'yam', name: 'Yellow yam 43lb Jamaica' },
  { id: 103, category_id: 'yam', name: 'PURPLE YAM HAWAI 30LB' },
  { id: 104, category_id: 'yam', name: 'Yam espino col' },
  { id: 105, category_id: 'apples', name: 'Fuji 80ct' },
  { id: 106, category_id: 'apples', name: 'Apple red 72' },
  { id: 107, category_id: 'apples', name: 'Apple gold 56ct' },
  { id: 108, category_id: 'apples', name: 'Apple green 56ct' },
  { id: 109, category_id: 'roots', name: 'MALANGA COCO' },
  { id: 110, category_id: 'roots', name: 'MALANGA WHITE 30lb' },
  { id: 111, category_id: 'roots', name: 'MALANGA LILA 30lb' },
  { id: 112, category_id: 'roots', name: 'Turmeric yellow 30lb' },
  { id: 113, category_id: 'roots', name: 'Taro EDDO' },
  { id: 114, category_id: 'roots', name: 'Nagaimo root' },
  { id: 115, category_id: 'roots', name: 'Yuca 33lb turbana' },
  { id: 116, category_id: 'roots', name: 'YUCA ECU 35LB' },
  { id: 117, category_id: 'roots', name: 'Eddo turbana' },
  { id: 118, category_id: 'squash', name: 'Chayote green TURBANA' },
  { id: 119, category_id: 'squash', name: 'Chayote black turbana 40lb' },
  { id: 120, category_id: 'squash', name: 'Squash Pipian 35lb' },
  { id: 121, category_id: 'squash', name: 'BLACK Chayote Guate 35LB' },
  { id: 122, category_id: 'squash', name: 'Squash tatume' },
  { id: 123, category_id: 'squash', name: 'Bin Black Ayote Guate LB' },
  { id: 124, category_id: 'herbs', name: 'Epazote' },
  { id: 125, category_id: 'herbs', name: 'Culantro 10x4 Bunches' },
  { id: 126, category_id: 'herbs', name: 'Cilantro 60CT mex' },
  { id: 127, category_id: 'herbs', name: 'Callao' },
  { id: 128, category_id: 'herbs', name: 'Hierba Mora' },
  { id: 129, category_id: 'herbs', name: 'Hierba Chipilin' },
  { id: 130, category_id: 'herbs', name: 'POTATOE LEAF 20LB' },
  { id: 131, category_id: 'herbs', name: 'JUTE LEAF' },
  { id: 132, category_id: 'herbs', name: 'BASIL MEX 12LB' },
  { id: 133, category_id: 'herbs', name: 'Basil Hawai 14lb' },
  { id: 134, category_id: 'herbs', name: 'Rosemary' },
  { id: 135, category_id: 'herbs', name: 'Ruda plant' },
  { id: 136, category_id: 'herbs', name: 'Mint 16x1lb' },
  { id: 137, category_id: 'herbs', name: 'Lemon Grass' },
  { id: 138, category_id: 'garlic', name: 'Garlic Sleeve WHITE China' },
  { id: 139, category_id: 'garlic', name: 'Garlic peeled 4/5lb' },
  { id: 140, category_id: 'garlic', name: 'Garlic peeled 20/1lb' },
  { id: 141, category_id: 'garlic', name: 'Ginger CHINA 30LB' },
  { id: 142, category_id: 'garlic', name: 'Ginger Organic Peru 30lb' },
  { id: 143, category_id: 'tomatoes', name: 'Tomate Jumbo' },
  { id: 144, category_id: 'tomatoes', name: 'Tomatillo green' },
  { id: 145, category_id: 'tomatoes', name: 'Tomatoe 5x6' },
  { id: 146, category_id: 'others', name: 'Cinamon loose 50lb' },
  { id: 147, category_id: 'others', name: 'Tortilla El Milagro 36CT' },
  { id: 148, category_id: 'others', name: 'HONEY 12CT' },
  { id: 149, category_id: 'others', name: 'Cacahuate 40lb' },
  { id: 150, category_id: 'others', name: 'Tamarindo 25LB' },
  { id: 151, category_id: 'others', name: 'CORN HUSK' },
  { id: 152, category_id: 'others', name: 'Jamaica Flower 25lb' },
  { id: 153, category_id: 'others', name: 'Chicharron tiras 10lb' },
  { id: 154, category_id: 'others', name: 'Baby bok choy 30lb mex' },
  { id: 155, category_id: 'others', name: 'Shangai 30lb mex' },
  { id: 156, category_id: 'others', name: 'Yuchoi 30lb mex' },
  { id: 157, category_id: 'others', name: 'Baby mustard 30lb mex' },
  { id: 158, category_id: 'others', name: 'Chinese broccoli' },
  { id: 159, category_id: 'others', name: 'Pepper scotch jamaica' },
  { id: 160, category_id: 'others', name: 'Montoi fl' },
  { id: 161, category_id: 'others', name: 'Pumpking leaf 12 bunch' },
]

export const CAT_COLORS = ['#16a34a','#ca8a04','#ea580c','#db2777','#f97316','#eab308','#dc2626','#059669','#7c3aed','#92400e','#b91c1c','#78350f','#4d7c0f','#065f46','#a16207','#475569','#0ea5e9','#8b5cf6']
export const CAT_EMOJIS  = ['🥑','🍌','🥭','🍓','🍈','🍋','🌶','🥬','🧅','🍠','🍎','🌿','🫑','🌱','🧄','📦','🫐','🍇']
